server:
  port: 5000

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/security?useSSL=true
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  #    url: jdbc:h2:mem:testdb
  #    driver-class-name: org.h2.Driver
  #    username: sa
  #    password:
  #  h2:
  #    console:
  #      enabled: true

  jpa:
    properties:
      hibernate: org.hibernate.dialect.MySQL5Dialect

    hibernate:
      ddl-auto: update

#    database-platform: org.hibernate.dialect.H2Dialect